name: Create Markdown

on:
  issues:
    types: [opened]

jobs:
  create-file:
    if: github.event.label
    runs-on: ubuntu-latest

    env:
      GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_ISSUE_CREATED_AT: ${{ github.event.issue.created_at }}
      GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
      GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
      GITHUB_ISSUE_USER: ${{ github.event.issue.user.login }}
      GITHUB_ISSUE_URL: ${{ github.event.issue.html_url }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create issue as Markdown file for Profissional Experience
        if: github.event.label.name == 'experiencia_profissional'
        run: |
          chmod +x ./scripts/create_experiencia_profissional.sh
          ./scripts/create_experiencia_profissional.sh
        shell: bash

      - name: Create issue as Markdown file for Volunteer Experience
        if: github.event.label.name == 'experiencia_voluntaria'
        run: |
          chmod +x ./scripts/create_experiencia_volunteer.sh
          ./scripts/create_experiencia_volunteer.sh
        shell: bash

      - name: Create issue as Markdown file for Project Experience
        if: github.event.label.name == 'experiencia_em_projeto'
        run: |
          chmod +x ./scripts/create_experiencia_project.sh
          ./scripts/create_experiencia_project.sh
        shell: bash

      - name: Create issue as Markdown file for Post
        if: github.event.label.name == 'post'
        run: |
          chmod +x ./scripts/create_post.sh
          ./scripts/create_post.sh
        shell: bash

      - name: Create issue as Markdown file for Qualification
        if: github.event.label.name == 'qualification'
        run: |
          chmod +x ./scripts/create_qualification.sh
          ./scripts/create_qualification.sh
        shell: bash

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Create post ${{ github.event.issue.name }}"
          branch: main

